name = "Cobblemon Create Edition"
author = "Neureka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0a8d95fc8e8727593750a085608eaa55e31ccd65d1f359abd4aaef917dbb6bb"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
