name = "Cobblemon Create Edition"
author = "Neureka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8236bcff951610000d21ecfc63530dd68851d9283216df21ec6c869a0ac51115"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
