name = "Cobblemon Create Edition"
author = "Neureka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbc2e1239adf7155d51ee4ad36ee63d32461beccf421dff019869c843b78a2af"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
